version: '2'

services:
  nginx_plans:
    build: ./nginx
    ports:
     - 8000:80
    volumes:
    - ../crm_plans_backend:/data/crm_plans/httpdocs
    depends_on:
    - mysql_plans
    - php-fpm
  shell_plans:
    build: ./shell
    container_name: shell_plans
    volumes:
    - ../crm_plans_backend:/data/crm_plans/httpdocs
    depends_on:
    - mysql_plans
    - php-fpm
  php-fpm:
    build: ./php-fpm
    volumes:
    - ../crm_plans_backend:/data/crm_plans/httpdocs
  phpmyadmin_plans:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_plans
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80
    volumes:
     - /sessions
    external_links:
        - mysql
    depends_on:
    - mysql_plans
  mysql_plans:
    image: 'percona:5.6'
    volumes:
     - ./mysqldata:/var/lib/mysql
     - ./percona/my.cnf:/etc/my.cnf
    environment:
      MYSQL_DATABASE: 'crm_plans'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
    ports:
      - 52000:3306
  artisan_plans:
    build: ./artisan
    volumes:
    - ../crm_plans_backend:/data/crm_plans/httpdocs
    depends_on:
     - mysql_plans


